services:
  doppler-indexer-database:
    image: postgres:16.6
    environment:
      # Database credentials
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: default
      # Performance tuning parameters
      POSTGRES_INITDB_ARGS: "--data-checksums"
    command: >
      postgres
        -c shared_buffers=256MB
        -c work_mem=16MB
        -c maintenance_work_mem=64MB
        -c effective_cache_size=768MB
        -c max_connections=100
        -c random_page_cost=1.1
        -c max_parallel_workers_per_gather=4
        -c max_parallel_workers=8
        -c synchronous_commit=off
        -c wal_writer_delay=10ms
        -c max_wal_size=1GB
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  doppler-indexer:
    image: konistudio/doppler-v3-indexer:base-sepolia
    depends_on:
      - doppler-indexer-database
    environment:
      DATABASE_SCHEMA: v1
      DB_URL: postgresql://postgres:postgres@doppler-indexer-database:5432/default
      IPFS_URL: https://ipfs.w3s.link/ipfs
    restart: always
    ports:
      - "3011:42069"

  doppler-indexer-graphql:
    image: konistudio/doppler-v3-indexer:base-sepolia
    depends_on:
      - doppler-indexer-database
    environment:
      DATABASE_SCHEMA: v1
      DB_URL: postgresql://postgres:postgres@doppler-indexer-database:5432/default
      IPFS_URL: https://ipfs.w3s.link/ipfs
    restart: always
    entrypoint: []
    command: ["bun", "serve"]
    ports:
      - "3012:42069"

volumes:
  postgres_data:
    driver: local
