version: "3.3"

services:
  doppler-indexer-database:
    image: postgres:16.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  doppler-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RPC_BASE_SEPOLIA=https://base-sepolia.g.alchemy.com/v2/pzJndNB7vlHhdvQ2a41q7
      - DATABASE_URL=postgresql://postgres:postgres@doppler-indexer-database:5432/default
    ports:
      - 42069:42069
    depends_on:
      - doppler-indexer-database
